name: Import from Google Drive

on:
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  import-from-drive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download File from Google Drive
        run: |
          FILE_ID="1OREZTWPIY9b2-v3sWTo-RF5ZEU3K8bzh"
          FILE_NAME="mivia_db4.zip"  # Change to the desired file name

          curl -L -o $FILE_NAME "https://drive.google.com/uc?id=$FILE_ID"

      - name: Commit Changes
        run: |
          git config --global user.email "isaac4088@gmail.com"
          git config --global user.name "Aizeek"

          git add $FILE_NAME
          git commit -m "Add $FILE_NAME"
          git push
